### ISSUE TITLE
Configure website for SEO

### ISSUE THREAD

**Issue by sarthak-sehgal** [biojs/biojs-frontend#31]
Do we need Google analytics too [low priority]? @rowlandm @DennisSchwartz

**Comment by DennisSchwartz** [comment]
How much work do you think it would be? I think it would be very valuable to see how many people actually visit which bits of the website.

**Comment by sarthak-sehgal** [comment]
@DennisSchwartz I'll keep this part for the last. In case I'm not able to cover this before the final evaluation, I'll try to complete it after that. Google analytics will be of great help!
