### ISSUE TITLE
Add a small footer section?

### ISSUE THREAD

**Issue by DennisSchwartz** [biojs/biojs-frontend#36]
We could possibly add a small footer section to the page. It could just say 'BioJs 2018' or sth. But that's just personal preference :)

**Comment by rkpattnaik780** [comment]
I would like to work on this

**Comment by DennisSchwartz** [comment]
Hey @rkpattnaik780! 
Thanks for your interest in BioJS :)

You're very welcome to work on this. We don't have any designs at the moment so you have free reign on what it should look like. 

Maybe just assign this issue to yourself when you have the time to work on it and make a PR once you are ready for feedback/review.

Looking forward to it!

And let us know if you have any questions.

**Comment by aaryan01** [comment]
@rkpattnaik780 Are you still working on this?

**Comment by Nikhil-Vats** [comment]
I am working on this.
