### ISSUE TITLE
Put in tutorials for creating your own component

### ISSUE THREAD

**Issue by rowlandm** [biojs/biojs-frontend#46]
Base it off the old documentation - Dennis should be able to find it.

Will need to highlight that this information may be out of date.

**Comment by DennisSchwartz** [comment]
I've started looking for it, but it's well hidden ;)

**Comment by DennisSchwartz** [comment]
Since @yochannah redeployed the edu pages I consider this done for now. I will create a new issue to update the tutorials for when we agree on a new structure.
