### ISSUE TITLE
Port to react, Pwa support ; improve UI/UX and reduce excessive white space

### ISSUE THREAD

**Issue by shubhamkakkar** [biojs/biojs-frontend#60]
React Adv :
1. Prevention redundant usage of components by either using .map() or HOC --(.map() better than for --> in vue - v-for has to be used)--
2.Virtual Dom flexibility
3. Number of available options to implement a particular set of code, as compared to vue

--- UI ---
Use less white spacees
Map dialogue box on Home screen is can be designed with more flexibility to improve user interface with the diagram
Minimalistic designing could be implied
Navbar Items placing can be improved
Testimonials presentation could be highlighted in much better way

**Comment by DennisSchwartz** [comment]
Sorry, we just had someone work 3 months to build it in Vue. We're not porting it to react.

If you want, feel free to create a React version, if it fulfills all the requirements we'd be happy to move over.

For the UI issues you listed, you're welcome to create separate issues for those and even more welcome to make PRs :)

**Comment by shubhamkakkar** [comment]
So would you be making another repository for react under the organization for bioJS project ?
